name: CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Validate data
        uses: 3scale/ajv
        with:
          args: --errors=text -s data/schema.json -d data/data.json
